name: garafy_workflow
on:
  push:
     branches: [ master ]

jobs:
  job_one:
      name: Deploy
      runs-on: ubuntu-latest
      steps:
      - name: deploying garafy project
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DEVSERVER_IP}}
          username: ${{secrets.DEVSERVER_USER}}
          key:  ${{secrets.DEVSERVER_SECRET}}
          port: 22
          script: |
            cd /var/www/html/garafy/
            git checkout .
            git pull origin master
            composer install
            npm install
            npm run prod
            php artisan cache:clear
            rm -R storage/framework/views/*.php


